config:
  version: 20180117-DEV

server:
  port: 8083

jdbc:
  master: jdbc:mysql://47.98.123.156:3306/test&serverTimezone=Hongkong
  slave: jdbc:mysql://47.98.123.156:3306/test&serverTimezone=Hongkong
  username: root
  password: Zbw123456|
  testOnBorrow: true
  initSize: 5
  minIdle: 1
  maxActive: 20
  dataSourceShard:
    "0":
      id: 0
      url: jdbc:mysql://47.98.123.156:3306/mydemo1&serverTimezone=Hongkong
    "1":
      id: 1
      url: jdbc:mysql://47.98.123.156:3306/mydemo2&serverTimezone=Hongkong
    "2":
      id: 2
      url: jdbc:mysql://47.98.123.156:3306/mydemo3&serverTimezone=Hongkong

redis:
  database: 0
  host: 47.98.123.156
  password: Zbw123456|
  port: 6379
  pool:
    max-active: 8
    min-idle: 0
    max-wait:  -1
    max-idle: 8
rabbitmq:
  host: 47.98.123.156
  port: 15672
  username: guest
  password: guest


#redis:
#    maxIdle: 8
#    minIdle: 1
#    maxActive: 300
#    maxWait: 1000
#    timeout: 0
#    sentinel:
#      master:
#      nodes:

#kafka:
#    brokers:
#    zkNodes:
#    zkPort: 2181
#    brokerPort: 9092

#mq:
#   broker:
#      url: failover:(tcp://ip:61616,tcp://ip:61616)?jms.useAsyncSend=true&randomize=false&backup=true&jms.prefetchPolicy.queuePrefetch=1
#   username:
#   password:
#   backup: true

eureka:
  defaultZone: http://localhost:6001/eureka

sleuth:
  sampler:
    percentage: 0.2

wizard:
  app:
    sendEmailWhenStart: false
    sendEmailWhenError: false
    checkSign: false
    env: dev
    port: 7061
    metricEnable: false
    metricsPrefix: "wizard-service"
    metricsPeriod: 15
    metricsHost: ip
    metricsPort: 8125
    metricsMemFreeRatio: 0.9
    maxPageSize: 50

#quartz:
#  app:
#    sendEmailWhenStart: false
#    sendEmailWhenError: false
#    checkSign: false
#    env: dev
#    port: 7052
#    zk_address: ip:2181,ip:2181,ip:2181
#    jobtime:
#      erpshopjob: "0/5 * * * * ?"
#      shoptablejob: "0/30 * * * * ?"

zuul:
  app:
    sendEmailWhenStart: false
    sendEmailWhenError: false
    checkSign: false
    env: dev111
    port: 7101
    ignoreTokenCheckUrls: /ping.json,/info.json,/user/signOn,/user/switchToken,/user/permission,/user/switchSystem,/mposmsy
    internetDomain: .mwee.cn|.9now.net|.mwpos.cn
    metricEnable: false
    metricsPrefix: "winpos.zuul"
    metricsPeriod: 15
    metricsHost: ip
    metricsPort: 8125
    maxPageSize: 50

#zipkin:
#  port: 7004
#  config:
#    metricEnable: false
#    metricsPrefix: "winpos.zipkin"
#    metricsPeriod: 15
#    metricsHost: 1ip
#    metricsPort: 8125
#    esUrl: http://ip:9200
#
#hystrix-dashboard:
#  port: 7003
#  config:
#    metricEnable: false
#    metricsPrefix: "winpos.hystrix"
#    metricsPeriod: 15
#    metricsHost: 1ip
#    metricsPort: 8125
#
#turbine:
#  port: 7005
#  config:
#    metricEnable: false
#    metricsPrefix: "winpos.turbine"
#    metricsPeriod: 15
#    metricsHost: ip
#    metricsPort: 8125
